TissueImageAnalytics/tiatoolbox

AUTHORS.md, HISTORY.md
- Add author list
- Add contributions
- Update History.md
=> DOC: Add authors contribution

HISTORY.md, setup.cfg, setup.py, tiatoolbox/__init__.py
- Adds feature `read_region` to read a small region from whole slide images
- Adds feature `save_tiles` to save image tiles from whole slide images
- Adds feature `imresize` to resize images
- Adds feature `transforms.background_composite` to avoid creation of black tiles from whole slide images.
- None 
- Adds `pandas` as dependency
=> REL: Pre release 0.3.0

.travis.yml, setup.cfg, tests/test_tiatoolbox.py, tox.ini
Fix travis, tox and flake8 settings for travis bugs
=> BUG: Fix travis, tox and flake8 settings 

LICENSE.md, README.md
I have added the full text verbatim of the [GLP v3 licence](https://www.gnu.org/licenses/gpl-3.0.en.html) in [`LICENCE.md`](https://github.com/TIA-Lab/tiatoolbox/blob/docs-licensing/LICENSE.md) and also added to the [readme](https://github.com/TIA-Lab/tiatoolbox/tree/docs-licensing#license). At the bottom of the GPL licence there are some guidance notes (included below) which suggest adding a short statement to each source file.
```
How to Apply These Terms to Your New Programs
If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.
To do so, attach the following notices to the program.  It is safest
to attach them to the start of …
```
=> DOC: Add License Information

requirements.conda.yml, requirements.dev.conda.yml, requirements.txt, requirements.win64.conda.yml, requirements_dev.txt, setup.py
=> DEP: Remove pathos as dependency

requirements.dev.conda.yml
- Add pytest and pytest-runner to requirements.dev.conda.yml
=> DEV: Hotfix pytest conda dev

tiatoolbox/utils/misc.py
Task: Hotfix-develop
- Fix windows path issues in misc.save_ext ad misc.save_yaml
=> Hotfix paths develop

tests/test_tiatoolbox.py
- Replace JP2 image with a small sized image for pytest
=> TST: Update JP2 image for pytest

README.md, requirements.conda.yml, requirements.dev.conda.yml, requirements.txt, requirements.win64.conda.yml, requirements_dev.txt, setup.py
- Clarify installation instructions
- Pin incompatible dependency numpy <= 1.19.3
=> DOC: Update Installation instructions in README.md

.travis.yml
=> DEV: Run travis only on PR

requirements.conda.yml, requirements.dev.conda.yml, requirements.txt, requirements.win64.conda.yml, requirements_dev.txt, setup.py
- Add Colab and Kaggle links to allow user to run notebooks directly on colab or kaggle.
=> DOC: Add Colab and Kaggle links

docs/usage.rst, tests/test_wsireader.py, tiatoolbox/dataloader/wsireader.py
Rename VFReader to VirtualWSIReader and apply a small edit to class docstring.
=> MAINT: Rename VFReader to VirtualWSIReader

.travis.yml, HISTORY.md, setup.cfg, setup.py, tiatoolbox/__init__.py
- Fix test.pypi deployment on pre-release
=> BUG: Fix test.pypi deployment on pre-release

examples/example_stainnorm.ipynb, examples/example_wsiread.ipynb, setup.py
- Add `scikit-image` as dependency in `setup.py`
- Update notebooks to install dependencies
=> HOT: Hotfix requirements

HISTORY.md, setup.cfg, setup.py, tiatoolbox/__init__.py
- Add `scikit-image` as dependency in `setup.py`
- Update notebooks to install dependencies
=> REL: Pre-release 0.5.1

README.md
This fixes the logo loading on pypi.
=> DOC: Change Logo URL To Be Absolute

docs/usage.rst, tiatoolbox/dataloader/save_tiles.py, tiatoolbox/dataloader/slide_info.py, tiatoolbox/dataloader/wsimeta.py, tiatoolbox/dataloader/wsireader.py, tiatoolbox/tools/stainextract.py, tiatoolbox/tools/stainnorm.py, tiatoolbox/utils/image.py, tiatoolbox/utils/misc.py, tiatoolbox/utils/transforms.py
- Improve docstring
- Add links
- Check for typos
- Remove redundant input parameters
- Add missing input parameters
- Consistent spacing
=> DOC: Improve docstring

tests/test_patch_extraction.py, tests/test_utils.py, tests/test_wsireader.py, tiatoolbox/tools/patchextraction.py, tiatoolbox/utils/misc.py, tiatoolbox/wsicore/wsireader.py
- Rearrange FixedWindowPatchExtractor attributes for feature implementation.
- Addtional attribute `current_location` added to FixedWindowPatchExtractor .
=> NEW: Feature Fixed Window Patch Extraction

README.md
- Structure the chapters in documentation better
=> DOC: Restructure chapters in documentation

tests/test_models.py, tests/test_utils.py, tiatoolbox/models/classification/pretrained_info.py, tiatoolbox/utils/misc.py
=> HOTFIX: Update model URLs to fix tests 

.pre-commit-config.yaml, .travis.yml, CONTRIBUTING.rst, docs/installation.rst, requirements.conda.yml, requirements.dev.conda.yml, requirements.txt, requirements.win64.conda.yml, requirements_dev.txt, setup.py, tox.ini
- Drop support for python 3.6
- Update minimum requirement to python 3.7
- Add support for python 3.9
=> DEV: Update minimum requirement to python 3.7

tests/models/test_semantic_segmentation.py, tiatoolbox/data/remote_samples.yaml
- Reduce the time for dummy tests by changing the resolutions.
=> DEV: Simplify tests for semantic segmentation engine

README.md, requirements.dev.conda.yml, setup.py
- Update instructions in `README.md` for developers.
=> [skip travis] DOC: Update instructions in `README.md` for developers.

docs/installation.rst, requirements.conda.yml, requirements.dev.conda.yml, requirements.txt, requirements.win64.conda.yml, requirements_dev.txt, setup.py, tests/models/test_nucleus_instance_segmentor.py, tiatoolbox/models/engine/nucleus_instance_segmentor.py
Replace pygeos with shapely to resolve the GEO binary installation issue.
=> ENH: Swap pygeos to shapely

tests/test_slide_info.py, tests/test_slide_thumbnail.py, tests/test_wsireader.py, tiatoolbox/cli/slide_info.py, tiatoolbox/cli/slide_thumbnail.py, tiatoolbox/utils/misc.py
- Fix slide-thumbnail in cli to save file
- Update cli slide-thumbnail to run on a directory
- Default to save mode in slide-thumbnail
=> BUG: Fix CLI For Slide-Thumbnail To Save File

docs/Makefile, docs/conf.py, docs/latex_preamble.tex, docs/notebooks.rst, tiatoolbox/annotation/storage.py, tiatoolbox/utils/image.py
To fix the unicode encoding error when build.
=> [skip travis] DOC: Change PDF Build Engine

examples/05-patch-prediction.ipynb, examples/full-pipelines/slide-graph.ipynb
=> [skip travis] BUG: Fix Kaggle error with bash

CITATION.cff, README.md
- Add doi to README and CITATION
=> [skip travis] DOC: Add doi to README and CITATION

CITATION.cff, docs/index.rst
- Fix index file on readthedocs
- Fix citation doi indent
=> [skip travis] DOC: Fix index file on readthedocs

.deepsource.toml, tests/test_exceptions.py, tests/test_wsireader.py, tiatoolbox/models/architecture/hovernetplus.py, tiatoolbox/models/architecture/unet.py, tiatoolbox/utils/misc.py, tiatoolbox/utils/visualization.py
- Fix DeepSource errors
- FLK-D202
- FLK-D207
- PY-W0069
=> BUG: Fix DeepSource errors

tests/test_utils.py, tiatoolbox/utils/__init__.py, tiatoolbox/utils/env_detection.py
@shaneahmed  and @ghadjigeorghiou, can you please confirm that this works for you.
=> BUG: Pixman Version Check

README.md, tests/test_utils.py, tiatoolbox/utils/misc.py, whitelist.txt
- Fix flake8 errors and typos in misc.py
=> DEV: Fix Flake8 Errors And Typos In `misc.py`

tiatoolbox/tools/stainextract.py, tiatoolbox/tools/stainnorm.py, tiatoolbox/utils/transforms.py
- Fix flake8 bugs for `tiatoolbox/utils/transforms`
=> DEV: Fix Flake8 Errors And Typos In `transforms.py`

README.md, tiatoolbox/models/architecture/hovernet.py, tiatoolbox/wsicore/wsireader.py, tox.ini
- Update `tiatoolbox` according to black v22.1.0
=> DEV: Update to latest `black` format

tiatoolbox/tools/stainextract.py, whitelist.txt
- Fix flake8 errors and typos in `stainextract.py`
=> DEV: Fix Flake8 Errors And Typos In `stainextract.py`

README.md
- Remove duplicate conda badge
=> [skip travis] DOC: Remove duplicate conda badge

.github/dependabot.yml
=> DEV: Create dependabot.yml

docs/installation.rst
- Update the installation docs with instructions on how to setup tiatoolbox docker container.
=> DOC: Update docs with Docker instructions

tiatoolbox/annotation/dsl.py, tiatoolbox/annotation/storage.py
- Make line wrapping consistent
- Make indentation consistent
- Fix typos
=> DOC: Tidy Annotation Docstrings

tiatoolbox/wsicore/save_tiles.py, tiatoolbox/wsicore/slide_info.py, tiatoolbox/wsicore/wsimeta.py, tiatoolbox/wsicore/wsireader.py
- Make line wrapping consistent
- Make indentation consistent
=> DOC: Tidy wsicore Docstrings

tests/models/test_arch_micronet.py, tiatoolbox/data/pretrained_model.yaml, tiatoolbox/models/architecture/micronet.py
- Update micronet.py docstring
- Rename models name according to naming convention.
=> DOC: Update micronet.py docstring

tiatoolbox/tools/graph.py, tiatoolbox/tools/patchextraction.py, tiatoolbox/tools/pyramid.py, tiatoolbox/tools/scale.py, tiatoolbox/tools/stainaugment.py, tiatoolbox/tools/stainextract.py, tiatoolbox/tools/stainnorm.py, tiatoolbox/tools/tissuemask.py
- Wrap Lines
- Fix typos
- Make indentation consistent
=> DOC: Tidy Tools Docstrings

tests/test_utils.py, tests/test_wsireader.py, tiatoolbox/wsicore/wsireader.py
- Add tests to improve coverage for `misc` and `wsireader`
=> TST: Add tests for `misc` and `wsireader`

AUTHORS.md, CITATION.cff, HISTORY.md, setup.cfg, setup.py, tiatoolbox/__init__.py
- Bump version: 1.0.1 → 1.1.0
- Updates AUTHORS.md
- Adds DICOM Support.
- Updates license to more permissive BSD 3-clause.
- Adds [MicroNet](https://doi.org/10.1016/j.media.2018.12.003) model.
- Improves support for `tiff` files.
- Adds a check for tiles in a TIFF file when opening.
- Uses OpenSlide to read a TIFF if it has tiles instead of OpenCV (VirtualWSIReader).
- Adds a fallback to tifffile if it is tiled but openslide cannot read it
(e.g. jp2k or jpegxl tiles).
- Adds support for multi-channel images (HxWxC).
- Fixes performance issues in `semantic_segmentor.py`.
- Performance gain measurement: 21.67s (new) vs 45.564 (old) using a 4k x 4k WSI.
- External Contribution from @ByteHexler.
- Adds benchmark for Annotations Store.
- None
- Enhances the error messages to be more …
=> REL: Release 1.1.0

.pre-commit-config.yaml, .travis.yml, CONTRIBUTING.rst, docs/installation.rst, pyproject.toml, requirements.conda.yml, requirements.dev.conda.yml, requirements.win64.conda.yml, setup.py, tests/test_annotation_stores.py, tox.ini
- Remove support for python 3.7 to allow using latest version of image codecs and some advanced features.
=> DEV: Depreciate Support For Python 3.7.

tests/models/test_hovernetplus.py
- Fix flake8 errors in `tests_hovernetplus.py`
=> DEV: Fix Flake8 Errors and Typos in `tests_hovernetplus.py`

tests/test_save_tiles.py, tiatoolbox/models/architecture/vanilla.py, whitelist.txt
- Fix flake8 errors and typos in `tests\test_save_tiles.py`
=> DEV: Fix Flake8 Errors and Typos in `tests\test_save_tiles.py`

tiatoolbox/models/engine/patch_predictor.py
=> BUGFIX: Fixing for Merging Patch Predictor Output

.travis.yml, CONTRIBUTING.rst, docs/installation.rst, pyproject.toml, requirements.conda.yml, requirements.dev.conda.yml, requirements.win64.conda.yml, setup.py, tox.ini
=> NEW: Add Python 3.10 Support

tests/models/test_patch_predictor.py, tests/test_stainnorm.py, tests/test_tissuemask.py
- Fix PT011 pytest.raises() is too broad, set the match parameter.
=> DEV: Fix PT011 Pytest Raises is Too Broad

tests/models/test_multi_task_segmentor.py, tests/models/test_patch_predictor.py, tests/models/test_semantic_segmentation.py, tests/test_init.py, tests/test_tissuemask.py, tiatoolbox/models/engine/nucleus_instance_segmentor.py, tiatoolbox/models/engine/semantic_segmentor.py
- Fix Flake8 PIE803, C408, PT015, PT015 and PT018 Errors.
=> DEV: Fix Flake8 PIE*, C408 and PT* Errors 

.github/workflows/python-package.yml
=> DEV: Run GitHub Actions on tags

.github/workflows/python-package.yml
=> [skip travis] DEV: Add tags to release

CITATION.cff, HISTORY.md, setup.cfg, setup.py, tiatoolbox/__init__.py
- Bump version: 1.2.0 → 1.2.1
- None
- None
- Fixes issues with dependencies
- Adds flask to dependencies.
- Fixes missing file in the python package
- Clarifies help string for show-wsi option
- Removes Travis CI
- GitHub Actions will be used instead.
- Adds pre-commit hooks to check requirements consistency.
- Adds GitHub Action to resolve conda environment checks on Windows and Ubuntu.
=> REL: Release 1.2.1

docs/algorithms/theory-idars.rst
This will remain the correct link (unless the file hierarchy structure is
changed), surviving merge with develop and then merge with master.
=> MAINT: Fix Link To Point To Master Branch

.pre-commit-config.yaml
- Set default_language_version to python 3.7
=> DEV: Fix Pre-commit Error

pre-commit/requirements_consistency.py
Refactoring suggestions to improve code readability.
=> MAINT: Refactor Requirements Consistency

tiatoolbox/utils/visualization.py
The solution suggested by user '[pcscp](https://github.com/pcscp)' appears working, I incorporated the same.
=> BUG: Fix Issue #410: Update colorbar_params arguments in overlay_prediction_mask function

tiatoolbox/wsicore/wsireader.py
=> DOC: Fix `WSIReader` docstring.

tiatoolbox/models/engine/semantic_segmentor.py
=> BUG: Fix Flake8 G200 Error

.pre-commit-config.yaml
- Remove flake8-sql checks as this is not being maintained.
- https://github.com/pgjones/flake8-sql/pull/21
=> DEP: Remove Flake8-SQL

.github/workflows/conda-env-create.yml, requirements_dev.txt
- Add `docs/requirements.txt` to `requirements_dev.txt`
=> DEV: Add `docs/requirements.txt` to `requirements_dev.txt`

tiatoolbox/utils/visualization.py
fixes the colorbar issue cropping up in test_visualization.py
=> BUG: Fix the `colorbar` Bug with `plt`

.github/workflows/pip-install.yml
=> DEV: Fix PIP Install Workflow

tiatoolbox/tools/__init__.py, tiatoolbox/tools/patchextraction.py, tiatoolbox/wsicore/wsireader.py
- Fix Circular import `wsireader`
=> DEV: Fix Circular import `wsireader`

tiatoolbox/annotation/storage.py, tiatoolbox/wsicore/wsireader.py
- Fix R505 flake8 error unnecessary elif after return statement.
=> BUG: Fix R505 Flake8 Error

CITATION.cff, setup.cfg
- Update bump2version config for citation and docker
=> DEV: Update bump2version config

.pre-commit-config.yaml, requirements_dev.txt
- Update isort version to 5.12.0 resolve pre-commit set up.
=> :pushpin: DEV: Update isort version

tests/models/test_arch_micronet.py, tests/models/test_feature_extractor.py, tests/models/test_patch_predictor.py
- Adjust thresholds to fix local tests on GPU with updated version of PyTorch
=> :white_check_mark: TST: Fix Local Tests for Windows/Linux

benchmarks/annotation_store_alloc.py, tiatoolbox/annotation/storage.py, tiatoolbox/models/architecture/nuclick.py, tiatoolbox/models/dataset/classification.py, tiatoolbox/models/engine/patch_predictor.py, tiatoolbox/models/engine/semantic_segmentor.py, tiatoolbox/tools/patchextraction.py, tiatoolbox/tools/pyramid.py, tiatoolbox/tools/registration/wsi_registration.py, tiatoolbox/utils/image.py, tiatoolbox/utils/misc.py, tiatoolbox/utils/visualization.py, tiatoolbox/wsicore/wsimeta.py, tiatoolbox/wsicore/wsireader.py
- Fix B028 No explicit stacklevel keyword argument found.
=> :bug: BUG: Fix B028 Flake8 Error

.github/workflows/docker-publish.yml, CITATION.cff, HISTORY.md, setup.cfg, setup.py, tiatoolbox/__init__.py
- Restricts dependency versions for long term stability of the current version
None
- Fix bug related to reading scikit-image
- Restricts dependency versions for compatibility
=> 🔖 REL: Release 1.3.3

README.md, docs/installation.rst
- Improve installation instructions
Documentation link: https://tia-toolbox.readthedocs.io/en/doc-improve-installation-instructions/installation.html
=> :memo: DOC: Improve Installation Instructions

requirements.txt
=> ➕ Add `joblib` As Dependency

tests/test_init.py
=> ✅ Add Tests For Lazy Import

examples/01-wsi-reading.ipynb, examples/03-tissue-masking.ipynb, examples/05-patch-prediction.ipynb, examples/07-advanced-modeling.ipynb, examples/10-wsi-registration.ipynb, examples/inference-pipelines/idars.ipynb, examples/inference-pipelines/slide-graph.ipynb
- Update notebook for Google Colab runs
=> [skip ci] :adhesive_bandage:  Update notebooks for Google Colab runs

README.md
Added some descriptive text between "getting started" and "all users" to give brief description of what TIAToolbox is and what it offers.
=> ✏️ Update `README.md`

tests/conftest.py, tests/test_save_tiles.py
- Improve tests reduce runtime
=> :white_check_mark: Improve Tests for `save_tiles` to Reduce Runtime

tiatoolbox/annotation/dsl.py, tiatoolbox/cli/common.py, tiatoolbox/cli/show_wsi.py, tiatoolbox/cli/stain_norm.py, tiatoolbox/cli/tissue_mask.py, tiatoolbox/visualization/tileserver.py
- Fix linter error in `cli`, `annotation` and `visualization` from #625
=> :rotating_light: Fix Linter Error in `cli`, `annotation` and `visualization` 

benchmarks/annotation_store_alloc.py, pyproject.toml, tests/models/test_arch_vanilla.py, tests/models/test_patch_predictor.py, tests/test_annotation_stores.py, tests/test_annotation_tilerendering.py, tests/test_graph.py, tests/test_metrics.py, tests/test_scale.py, tests/test_tileserver.py, tests/test_utils.py, tests/test_wsi_registration.py, tests/test_wsireader.py, tiatoolbox/tools/graph.py, tiatoolbox/utils/visualization.py
- Add "NPY" `NumPy-specific rules` checks
=> :rotating_light: Add "NPY" `NumPy-specific rules` Checks

.pre-commit-config.yaml, benchmarks/annotation_store_alloc.py, requirements/requirements_dev.txt, tests/models/test_abc.py, tests/models/test_arch_nuclick.py, tests/models/test_arch_unet.py, tests/models/test_dataset.py, tests/models/test_patch_predictor.py, tests/models/test_semantic_segmentation.py, tests/test_slide_info.py, tests/test_slide_thumbnail.py, tests/test_utils.py, tests/test_wsireader.py
- Upgrade `ruff` to version `0.0.280`
=> :arrow_up: Upgrade `ruff` to Version `0.0.280`

pyproject.toml
- Add `ruff` Checks for `06-semantic-segmentation`
=> [skip ci]🚨 Add `ruff` Checks for `06-semantic-segmentation`

.github/workflows/docker-publish.yml, CITATION.cff, HISTORY.md, setup.py, tiatoolbox/__init__.py
- ### Bug Fixes and Other Changes
- Fix dictionary changed size Error #626 (#605)
Full Changelog: https://github.com/TissueImageAnalytics/tiatoolbox/compare/v1.4.0...v1.4.1
=> :bookmark: Release v1.4.1

tests/test_init.py, tiatoolbox/__init__.py
- Add `ruff` checks tiatoolbox root
=> :rotating_light: `ruff` tiatoolbox root

.github/workflows/python-package.yml, .pre-commit-config.yaml, requirements/requirements_dev.txt
=> :arrow_up: Upgrade `ruff` to `0.0.284`

tiatoolbox/visualization/tileserver.py
- Add `flake8-annotations` to visualisation.
=> :rotating_light: Add `flake8-annotations` to `Visualization`

.github/workflows/python-package.yml, .pre-commit-config.yaml, requirements/requirements_dev.txt, tiatoolbox/models/engine/multi_task_segmentor.py
=> :arrow_up: Upgrade `ruff` to `0.0.285`

tiatoolbox/wsicore/wsimeta.py, tiatoolbox/wsicore/wsireader.py
- Fix `flake8-annotations` for `wsicore`
=> :rotating_light: Fix `flake8-annotations` for `wsicore`

tiatoolbox/models/engine/multi_task_segmentor.py, tiatoolbox/models/engine/nucleus_instance_segmentor.py, tiatoolbox/models/engine/patch_predictor.py, tiatoolbox/models/engine/semantic_segmentor.py, tiatoolbox/tools/patchextraction.py
- Add `flake8-annotations` Checks for `engine`
=> :rotating_light: Add `flake8-annotations` Checks for `engine`

.github/workflows/python-package.yml, .pre-commit-config.yaml, requirements/requirements_dev.txt
- Upgrade `ruff` to version `0.0.286`
=> :arrow_up: Upgrade `ruff` to version `0.0.286`

tests/test_docs.py, tests/test_graph.py, tests/test_patch_extraction.py, tests/test_pyramid.py, tests/test_save_tiles.py, tests/test_slide_info.py, tests/test_slide_thumbnail.py, tests/test_stainaugment.py, tests/test_stainnorm.py, tests/test_tiffreader.py, tests/test_tileserver.py, tests/test_tissuemask.py, tests/test_utils.py, tests/test_wsi_registration.py, tests/test_wsireader.py, tiatoolbox/enums.py
- Add `flake8-annotations` to All Except `tiatoolbox/annotations`
=> 🚨 Add `flake8-annotations` to All Except `tiatoolbox/annotations`

.github/workflows/mypy-type-check.yml, requirements/requirements_dev.txt, tiatoolbox/utils/exceptions.py
- Add `mypy` Checks to `exceptions.py`
=> :hammer: Add `mypy` Checks to `exceptions.py`

.github/workflows/mypy-type-check.yml, .pre-commit-config.yaml, pyproject.toml, tiatoolbox/typing.py, tiatoolbox/utils/env_detection.py
- Fix type error in `tiatoolbox/typing.py` and `tiatoolbox/utils/env_detection.py`
=> :hammer: Add `typing.py` and `env_detection.py` to `mypy` Type Check

.github/workflows/docker-publish.yml, CITATION.cff, HISTORY.md, pyproject.toml, setup.py, tiatoolbox/__init__.py
- Specifies compatible Python versions
- Fixes `tiatoolbox-feedstock` build for conda-forge release #763
**Full Changelog:** https://github.com/TissueImageAnalytics/tiatoolbox/compare/v1.5.0...v1.5.1
=> 🚑 Release 1.5.1

.github/workflows/mypy-type-check.yml, tiatoolbox/tools/graph.py, tiatoolbox/tools/pyramid.py, tiatoolbox/tools/tissuemask.py, tiatoolbox/utils/visualization.py
Add `mpypy` checks to:
- `tiatoolbox/tools/__init__.py`
- `tiatoolbox/tools/stainextract.py`
- `tiatoolbox/tools/pyramid.py`
- `tiatoolbox/tools/tissuemask.py`
- `tiatoolbox/tools/graph.py`
=> :hammer: `mypy` type check `tools/`

requirements/requirements.txt
- Update `wsidicom` dependency
=> 📌 Update `wsidicom` dependency

docs/requirements.txt
- Fix `docs/requirements.txt` for `sphinx-design`.
=> :pushpin: Fix `docs/requirements.txt` for `sphinx-design`

.github/workflows/python-package.yml, .pre-commit-config.yaml, requirements/requirements_dev.txt
=> :pushpin: Update `ruff` version.

requirements/requirements.txt, tiatoolbox/visualization/bokeh_app/main.py
Update for compatibility with bokeh 3.5
=> 📌 Fix Compatibility with `bokeh` Version `3.5.0`

tiatoolbox/annotation/storage.py, tiatoolbox/tools/graph.py, tiatoolbox/tools/patchextraction.py, tiatoolbox/tools/pyramid.py, tiatoolbox/tools/registration/wsi_registration.py, tiatoolbox/tools/stainaugment.py, tiatoolbox/tools/tissuemask.py, tiatoolbox/utils/misc.py, tiatoolbox/wsicore/wsireader.py
Revisited the files in `tools/`, and fixed the errors that were not detected previously.
=> 🧑‍💻 Fix `mypy` Type Error in `tiatoolbox/tools`

.github/workflows/mypy-type-check.yml, .github/workflows/pip-install.yml, .github/workflows/python-package.yml, .readthedocs.yml, requirements/requirements.txt
- Update test build for Ubuntu-24.04
- Update readthedocs build on Ubuntu-24.04
- Docker images need to be rebuilt for Ubuntu-24.04 for the next release
=> :hammer: Update test build for `Ubuntu-24.04`

tiatoolbox/cli/common.py
- Fix `mypy` Type Checks for `cli/common.py`
=> :bug: Fix `mypy` Type Checks for `cli/common.py`
