TissueImageAnalytics/tiatoolbox

- .coveragerc
- .travis.yml
- requirements_dev.txt
- tox.ini
I have added pytest-cov to requirements. This is an extension to pytest (also made by pytest) which generates code coverage reports which will enable us to verify which parts of the code are actually being tested. I have also updated the tox and Travis configuration to output the report to the Travis terminal output and generate an XML which is then uploaded to codecov.
To see an example report you can view the one for this branch here: https://codecov.io/gh/TIA-Lab/tiatoolbox/branch/feature-code-cov.
> Feature code cov

- .travis.yml
Looks like I accidentally removed a space in the configuration file for Travis which may have broken builds! This should fix it and the build should run on the PR. This is a very minor change and will merge in unless there are objections.
> Hotfix: Travis configuration missing space

- README.rst
- Add badges to readme for Read The Docs, Travis CI, PyPI.
- Move Heading below logo.
- Change heading to be raw HTML and be centred.
Opening as a PR to test that docs building is not adversely affected.
> DOC: Add Badges To Readme + Center Heading

- docs/usage.rst
- tests/test_tiatoolbox.py
- tiatoolbox/cli.py
- tiatoolbox/dataloader/save_tiles.py
- tiatoolbox/dataloader/slide_info.py
- tiatoolbox/dataloader/wsimeta.py
- tiatoolbox/dataloader/wsireader.py
- tiatoolbox/utils/exceptions.py
- tiatoolbox/utils/misc.py
- tiatoolbox/utils/transforms.py
- Restructure WSIReader as parent class to allow support to read whole slide images in other formats.
- Add OpenSlideWSIReader
- Add tests for OpenSlideWSIReader
- Add docs for OpenSlideWSIReader
> API: Restructure WSIReader to allow support for additional formats

- tiatoolbox/__main__.py
- tiatoolbox/cli.py
- tiatoolbox/dataloader/save_tiles.py
- tiatoolbox/dataloader/slide_info.py
- tiatoolbox/dataloader/wsimeta.py
- tiatoolbox/dataloader/wsireader.py
- tiatoolbox/tiatoolbox.py
- tiatoolbox/utils/exceptions.py
- tiatoolbox/utils/misc.py
- tiatoolbox/utils/transforms.py
Replaced the "2006, Blender Foundation" to "2020, TIALab, University of Warwick" in the licence info.
> update affiliation in the licence info

- HISTORY.md
- setup.cfg
- setup.py
- tiatoolbox/__init__.py
- Adds `OpenSlideWSIReader` to read Openslide image formats
- Adds support to read Omnyx jp2 images using `OmnyxJP2WSIReader`.
- New feature added to perform stain normalisation using `Ruifork`, `Reinhard`, `Vahadane`, `Macenko` methods and using custom stain matrices.
- Adds example notebook to read whole slide images via the toolbox.
- Adds `WSIMeta` class to save meta data for whole slide images. `WSIMeta` casts properties to python types. Properties from OpenSlide are returned as string. raw values can always be accessed via `slide.raw`. Adds data validation e.g., checking that level_count matches up with the length of the `level_dimensions` and `level_downsamples`. Adds type hints to `WSIMeta`.
- Adds exceptions `FileNotSupported` and `MethodNotSupported`
-  Restructures `WSIReader` …
> REL: Pre-release to develop

- tests/test_tiatoolbox.py
- tiatoolbox/dataloader/wsireader.py
Fixes the `get_thumbnail` function in `WSIReader`. It now uses `read_bounds` with the origin and the slide dimensions as the bounds.
> BUG: Fix Reading Thumbnail In WSIReader

- tests/test_wsireader.py
- tiatoolbox/dataloader/wsireader.py
The read bounds function for openslide was using the incorrect location for levels other than level 0. This has been fixed in the included commit. I am currently writing a test to detect and avoid this error in future.
> BUG: Fix 2 Bugs In read_region

- tests/test_utils.py
- tests/test_wsireader.py
- tiatoolbox/dataloader/wsireader.py
- tiatoolbox/utils/misc.py
This is a draft PR proposing adding some code to calculate the microns-per-picel (MPP) based off of standard TIFF tags.
This is useful in the case where slides and been modified and converted to standard tiles tiffs and use regular TIFF tags instead of putting metadata in the description field (or when created directly as regular tiled TIFFs). In this case openslide does not find the MPP. Examples of such images can be seen in the [PANDA Kaggle challenge dataset](https://www.kaggle.com/c/prostate-cancer-grade-assessment/data).
As always the MPP is not completely reliable. In the future, it would be good to have some method to sanity check the values e.g. to make sure a sensible range or train a model to predict from the image if missing etc.
Also fixes a couple of bugs where the reader …
> NEW: Fallback To Calculate MPP From Standard TIFF Tags

- tiatoolbox/dataloader/wsireader.py
- convert `bounds` to baseline reference frame in `WSIReader.save_tiles`
> HOTFIX: Fix save_tiles

- tiatoolbox/cli.py
Fix a bug in taking directory input for stainnorm operation. All files should be read from the input text if it is a directory instead of returning an empty list.
Note: It is a critical bug fix as it changed the syntax of default file types, which is a common input for all commands and that's why affects all other operations.
> BUG : Directory input for stainnorm operation

- Makefile
- requirements.dev.conda.yml
- requirements_dev.txt
Change recipe in Makefile for coverage to use pytest-cov instead of coverage. Pytest-cov supports multiprocessing and a few extra bits. Also added pytest-cov to dev requirements so that it will not throw and error when using the recipe. Also for consistency across testing (travis / tox is using pytest-cov and the env is slightly different when using coverage).
To generate test coverage locally run the make recipe:
```bash
$ make coverage
```
This will run the tests and collect coverage before opening the index in a web browser:
Clicking through to a file will show line-by-line coverage:
> DEV: Update HTML Coverage Recipe

- .pre-commit-config.yaml
- pyproject.toml
- requirements.dev.conda.yml
- requirements_dev.txt
- setup.cfg
- Added [pre-commit](https://pre-commit.com/#install) for easy setup of client-side git [hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) for [black code formatting](https://github.com/psf/black#version-control-integration) and flake8 linting.
- Added [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear) to pre-commit for catching potential deepsource errors.
Alternatively (or additionally) [black could be added as a GitHub action](https://github.com/psf/black#github-actions) to format on push or PR.
Could potentially add [Prettier](https://prettier.io/) for non python files (e.g. yaml etc), as used by black and other projects.
To set up pre commit on your clone of the repository simply check that you have pre-commit installed (from dev requirements or via homebrew …
> DEV: Add Pre-Commit

- tests/test_wsimeta.py
- tests/test_wsireader.py
- tiatoolbox/dataloader/wsimeta.py
- tiatoolbox/dataloader/wsireader.py
- Add caching to slide info property. This is done by checking if a private `self._m_info` exists and returning it if so, otherwise `self._info` is called to create the info for the first time (or to force regenerating) and the result is assigned to `self._m_info`. This could in future be made much simpler with the `functools.cached_property` decorator in Python 3.8+.
- Add `copy.deepcopy` when retuning info, i.e. return a copy. This prevents accidentally mutating the slide info object.
- Add cast around openslide property (ctype property map) to make it a python dictionary instead. This means that the resulting `WSIMeta` object does not contain any ctypes pointers and is therefore picklable.
- Add a setter for slide info for explicitly updating the info `WSIMeta` object.
- Update tests.
> ENH: Cache Slide Info Property

- docs/conf.py
- docs/usage.rst
- tests/test_utils.py
- tests/test_wsireader.py
- tiatoolbox/dataloader/slide_info.py
- tiatoolbox/dataloader/wsireader.py
- tiatoolbox/utils/misc.py
- tiatoolbox/utils/transforms.py
- Add a better microns per-pixel (MPP) from objective power estimation function (y = 10 / x) which is continuous and self-inverse i.e. 40 → 0.25, 0.25 → 40, 0.5 → 20, 20 → 0.5, 0.2534 → 39.46, 39.46 → 0.2534 etc.
- Add a method to estimate objective power from MPP but snap to common values e.g. 20x, 40x etc.
> NEW: Improve Metadata Estimation

- docs/usage.rst
- tests/test_wsireader.py
- tiatoolbox/dataloader/save_tiles.py
- tiatoolbox/dataloader/slide_info.py
- tiatoolbox/dataloader/wsimeta.py
- tiatoolbox/dataloader/wsireader.py
- tiatoolbox/tools/stainnorm.py
- Add `get_wsireader()` for simplified creation of WSIReader
- Add tests for `get_wsireader()`
- Rearrange `usage.rst` for better readability.
- Update `save_tiles`, `slide_info` and example notebooks to use the `get_wsireader()` function.
> ENH: Add `get_wsireader()` for simplified creation of WSIReader

- HISTORY.md
- setup.cfg
- setup.py
- tiatoolbox/__init__.py
- Update History for 0.5.0 release
- bump2version 0.5.0
- Adds `get_wsireader()` to return appropriate WSIReader.
- Adds new functions to allow reading of regions using WSIReader at different resolutions given in units of:
- microns per-pixel (mpp)
- objective lens power (power)
- pixels-per baseline (baseline)
- resolution level (level)
- Adds functions for reading regions are `read_bounds` and `read_rect`.
- `read_bounds` takes a tuple (left, top, right, bottom) of coordinates in baseline (level 0) reference frame and returns a region bounded by those.
- `read_rect` takes one coordinate in baseline reference frame and an output size in pixels.
- Adds `VirtualWSIReader` as a subclass of WSIReader which can be used to read visual fields (tiles).
- `VirtualWSIReader`  accepts ndarray or …
> REL: Pre-release 0.5.0

- tiatoolbox/dataloader/slide_info.py
Change the example given for slide_info() so as to make it work on windows.
> DOC: Fix Output Path file_path in Example of slide_info

- tests/conftest.py
Add a temporary change of URL for the JP2 test image in conftest.py and example_wsiread.ipynb.
> BUG: Update URL for JP2 Test Image

- docs/usage.rst
- tests/test_patch_extraction.py
- tiatoolbox/tools/patchextraction.py
- Change the class `FixedWindowPatchExtractor` name to  `SlidingWindowPatchExtractor` 
- get_patchextractor takes the `slidingwindow` as an argument. 
- Depreciate `VariableWindowPatchExtractor`
> API: changing `FixedWindowPatchExtractor` to `SlidingWindowPatchExtractor`

- tiatoolbox/utils/transforms.py
- tiatoolbox/wsicore/slide_info.py
- tiatoolbox/wsicore/wsireader.py
Modify the documentation for following:
- Use get_wsireader() instead of wsireader() in the [documentation](https://tia-toolbox.readthedocs.io/en/latest/usage.html)
- Replace file_name with file_path in the documentation of example of slide_info() function
- Include numpy import statement in the example of tiatoolbox.utils.transforms.background_composite
> DOC: Fix examples in module docstring

- docs/usage.rst
- tests/test_patch_extraction.py
- tiatoolbox/tools/patchextraction.py
- tiatoolbox/wsicore/wsireader.py
This PR is focused on `patchextraction` functionality to clean up some part, change the API, and adding new features to it.
The `SlidingWindowPatchExtraction` class will accept the `input_mask` argument to extract patches based on the regions that are highlighted in the `input_mask`. The `input_mask` can be a path to the desired mask mask, a numpy array, `VirtualWSIReader`, or `'auto'`. In case of `'auto'`, a tissue mask is automatically generated for the `input_image` using tiatoolbox `TissueMasker` functionality if the `input_image` is a real WSI, otherwise, no mask will be considered for patch extraction.
> ENH: Add functionality to read through mask in `patchextraction`

- .readthedocs.yml
Conda build on readthedocs causes build errors
To resolve the above issue, I have
- added requirements.txt in .readthedocs.yml 
- added apt-get installation for openjpeg and openslide
- removed conda build 
The result is much faster build time on readthedocs and the out of memory issue is resolved now.
> DEV: Use requirements file for readthedocs build

- .pre-commit-config.yaml
- setup.cfg
- whitelist.txt
I have compiled many extra checks for pre-commit, some of which are the same as those used by deepsource. Proposed new additions to pre-commit:
- isort: Sort and group imports (stdlibrary, 3rd party, current package)
- flake8-isort: Check import ordering
- flake8-comprehensions: Suggestions for better comprehensions
- flake8-mutable: Check for mutable default arguments
- flake8-use-fstring: Use of f-strings vs old style format strings
- flake8-simplify: Suggestions to simplify code
- pep8-naming: Check PEP8 class naming
- flake8-eradicate: Find dead/commented out code
- flake8-builtins: Check for built-ins being used as variables
- flake8-cognitive-complexity: Check max function complexity (set in setup.cfg)
- flake8-expression-complexity: Check max expression complexity (set in …
> DEV: Extra Pre-commit Checks

- HISTORY.md
- setup.cfg
- setup.py
- tiatoolbox/__init__.py
- Bump version: 0.6.0 → 0.7.0
- Drops support for python 3.6
- Update minimum requirement to python 3.7
- Adds support for python 3.9
- Adds `models` base to the repository. Currently, PyTorch models are supported. New custom models can be added. The tiatoolbox also supports using custom weights to pre-existing built-in models.
- Adds `classification` package and CNNPatchPredictor which takes predefined model architecture and pre-trained weights as input. The pre-trained weights for classification using kather100k data set is automatically downloaded if no weights are provided as input.
- Adds mask-based patch extraction functionality to extract patches based on the regions that are highlighted in the `input_mask`. If `'auto'` option is selected, a tissue mask is automatically generated …
> REL: Pre-release 0.7.0

- tests/test_patch_extraction.py
- tiatoolbox/tools/patchextraction.py
Current predictors or any functions rely on `get_coordinates` will have the patch coordinates extracted at requested resolution not at baseline of input wsi. However, `filter_coordinates` does not indicate that and thus the `mask_reader` (after being binded to read wrt to the source image metadata) will read at wrong resolution, thus filtering out wrong coordinates.
> BUG: Fix `filter_coordinates` read wrong resolutions

- tests/models/test_patch_predictor.py
- tiatoolbox/data/pretrained_model.yaml
- tiatoolbox/models/dataset/classification.py
- tiatoolbox/models/engine/patch_predictor.py
The current way patch predictor parses input arguments for reading is locked behind some very specific cases, and some time counter intuitive to figure out. Here, I ported over the definition and handling from semantic, which is more flexible, and simplified it for this specific niche case. The way input output configuration will be parsed going forward is as follow:
- `ioconfig` will supersed everything
- if `ioconfig` is not provided
- If `model` is pretrained (defined in `pretrained_model.yaml` )
- Use the yaml ioconfig
- Any other input patch reading arguments will overwrite the yaml ioconfig (at the same keyword).
- If `model` is not defined, all input patch reading arguments must be provided else exception will be thrown.
> BUG: Fix patch predictor io config delegation

- tests/models/test_dataset.py
- tiatoolbox/models/dataset/info.py
- Update links for katherdataset
- Use small sample for kather test. Full zip is only for local tests.
> DEV: Update links for Kather dataset

- setup.cfg
A suggestion to in crease the cognitive complexity limit. The current threshold can be triggered by simple things such as a few ifs in a row, especially as python doesn't use switch statements. We also have two other complexity checks in place.
> [skip travis] DEV: Increase Cognitive Complexity Limit In setup

- tiatoolbox/annotation/storage.py
Some slight differences in `ujson.dumps` and `json.dumps` arguments means that ujson cannot be used as a drop-in replacement for json.
This was causing an issue as this module was using ujson with options which are in standard library json dumps (separators kwarg) but not ujson. In future ujson, orjson or some other optimised json library could be used in place of built-in json for performance improvements but would mean adding another dependency.
> BUG: Remove ujson From Annotation Store

- tiatoolbox/annotation/storage.py
I would like to rename the 'boundary' column in the table used by SQLiteStore to 'geometry' and best to do this before it goes into a version published on pypi to avoid incompatibility between versions.
> ENH: Rename 'boundary' Column To 'geometry' & Rename Variables

- .readthedocs.yml
- docs/requirements.txt
- requirements_dev.txt
- Separate out readthedocs requirements to avoid python 3.7 requirements errors.
> DOC: Separate out readthedocs requirements 

- examples/01-wsi-reading.ipynb
- examples/03-tissue-masking.ipynb
- examples/05-patch-prediction.ipynb
- examples/07-advanced-modeling.ipynb
- examples/full-pipelines/slide-graph.ipynb
- examples/inference-pipelines/idars.ipynb
- examples/inference-pipelines/slide-graph.ipynb
- Update links to Colab, Git and Kaggle
> [skip travis] DOC: Update links to Colab, Git and Kaggle

- examples/05-patch-prediction.ipynb
- Update examples/05-patch-prediction
> [skip travis] DOC: Update examples/05-patch-prediction

- tests/models/test_hovernet.py
- tiatoolbox/data/pretrained_model.yaml
- tiatoolbox/models/architecture/hovernet.py
Add HoVer-Net model weights trained on both the CoNSeP and MoNuSAC datasets.
- path to weights updated in `pretrained_model.yml`
- added tests
> NEW: Add HoVer-Net CoNSeP and MoNuSAC models

- docs/pretrained.rst
- tiatoolbox/models/engine/nucleus_instance_segmentor.py
- tiatoolbox/models/engine/patch_predictor.py
- tiatoolbox/models/engine/semantic_segmentor.py
Include all pretrained model info in `pretrained.rst`
> [skip travis] DOC: Update docs for pretrained models

- README.md
> DOC: Fix README conda link

- tests/test_utils.py
- tiatoolbox/data/pretrained_model.yaml
- tiatoolbox/models/engine/nucleus_instance_segmentor.py
- Empty querry will make the program crash (this is depending on wsi/tile). This check should fix it.
- Banding issue (missing prediction) due to wrong removal handling, It is not yet clear why it happens as the larger images (12k x 12k atm) does not seem to be affected. Setting larger tile fixes it so this is an emergency fix. A follow up investigation is necessary.
> BUG: Fix Empty Query in Instance Segmentor

- tests/models/test_abc.py
- tests/models/test_dataset.py
- tests/models/test_multi_task_segmentor.py
- tests/models/test_nucleus_instance_segmentor.py
- tests/models/test_patch_predictor.py
- tests/models/test_semantic_segmentation.py
- tests/test_utils.py
- tiatoolbox/utils/env_detection.py
- whitelist.txt
There are several tests that have been marked to be skipped when running pytest because there were no way to check if they are run on Travis. Now we have the facility for detecting runtime flag in place, we can automatically flag which test to run on which conditions. This PR deals with tests that are related to Deep Learning Models (require GPU and Travis runtime check).
> MAINT: Setting Up Conditional Tests Using "pytest skipif"

- tests/test_annotation_stores.py
- tiatoolbox/annotation/dsl.py
- tiatoolbox/annotation/storage.py
It is possible that SQLite (e.g. versions <3.35) may not have math functions enabled (e.g. floor). This could break some queries e.g. those made using a DSL string including a floor division (//).
Added information to docs. See https://tia-toolbox.readthedocs.io/en/bug-sqlite-floor/_autosummary/tiatoolbox.annotation.dsl.html.
> BUG: Add User Warning For Missing SQLite Functions

- tests/test_graph.py
- tiatoolbox/tools/graph.py
This PR fixes some issues in graph.py
1. Fix typos in docstrings.
2. Fix typo in function name traingle -> triangle
3. Fix a bug in graph visualisation where some edges would not be drawn.
Some other things have been fixed as they were discovered during this PR:
1. Fix a bug in function to convert edge index to triangles (it would find the same triangle twice in a different order).
2. Add tests.
> BUG: Fix Graph Functions

- tests/test_patch_extraction.py
- tiatoolbox/tools/patchextraction.py
- Fix flake8 errors and typos in `patchextraction.py`
- Replace ValueError with a warning if empty list of points is passed.
> DEV: Fix Flake8 Errors And Typos In `patchextraction.py`

- .travis.yml
- tests/test_utils.py
- tiatoolbox/utils/env_detection.py
- tox.ini
- tox.ini modified to pass Travis variables which fixes the tests.
- Updated tests to run locally for Travis detection.
- Reduces Travis runtime by up to 5 mins per run.
> BUG: Fix Travis Detection 

- tiatoolbox/models/abc.py
- tiatoolbox/models/architecture/hovernet.py
- tiatoolbox/models/architecture/unet.py
- tiatoolbox/models/architecture/utils.py
- tiatoolbox/models/architecture/vanilla.py
- Update forward function for consistent input.
> DEV: Update forward function for consistent input

- requirements.dev.conda.yml
- requirements_dev.txt
- tox.ini
- [DEP: Bump flake8 from 3.7.8 to 4.0.1](https://github.com/TissueImageAnalytics/tiatoolbox/commit/4ba0c3ba4eda3f7a729707e9c53ea29372c6eb0d)
- [DEP: Bump twine from 1.14.0 to 3.8.0](https://github.com/TissueImageAnalytics/tiatoolbox/commit/1e63d9a857ec1eda03839fad5b812668d1dac248)
- [DEP: Bump bump2version from 0.5.11 to 1.0.1](https://github.com/TissueImageAnalytics/tiatoolbox/commit/d33fefba3269fbb96f0bef5d828bec2a2cf638ef)
- [DEP: Remove watchdog from dependency list](https://github.com/TissueImageAnalytics/tiatoolbox/commit/0ac321690b6730267a2e5619ce36675280d8eaba)
- [DEP: Bump coverage from 5.1 to 6.3.2](https://github.com/TissueImageAnalytics/tiatoolbox/commit/8c2d97fae5d201c315a6ef3e19c38d8372ad2da6)
- [DEP: Bump wheel from 0.33.6 to …
> DEV: Dependency upgrades

- requirements.conda.yml
- requirements.dev.conda.yml
- requirements.txt
- requirements.win64.conda.yml
- requirements_dev.txt
- setup.py
- tests/test_wsireader.py
- Update scikit image version to 0.19.1
> DEV: Update scikit-image Version

- tests/test_data.py
- tests/test_init.py
- tests/test_stainaugment.py
- tests/test_stainnorm.py
- tiatoolbox/data/__init__.py
- tiatoolbox/models/__init__.py
- tiatoolbox/models/architecture/idars.py
- tiatoolbox/visualization/tileserver.py
Tidy docstrings in data, annotation etc.
- Make line wrapping consistent.
- Make indentation consistent
- Remove unused import
> DOC: Tidy Miscellaneous Docstrings

- tests/models/test_arch_micronet.py
- tests/test_stainnorm.py
- tiatoolbox/data/pretrained_model.yaml
- tiatoolbox/models/architecture/micronet.py
Fix the stain normalisation CLI test which would dump output into the project root directory by specifying an output to a temporary test directory.
> TST: Make Stain Norm CLI Tests Use Temp Dir

- .gitignore
- Makefile
There was a bug in `make docs` where it would try to remove a directory `rm docs/_autosummary` without the required `-r` option. This has been fixed in this PR. Also,  a `clean-docs` command has been added in addition to including generated files in the .gitignore file.
> DEV: Fix Makefile Docs Command

- tests/test_annotation_stores.py
- tests/test_utils.py
- tiatoolbox/utils/misc.py
This is to satisfy Deepsource security issues and also avoid the user from accidentally overwriting files or writing to a directory that doesn't exists.
> MAINT: Add Checks To User Provided Paths

- README.md
- tests/models/test_feature_extractor.py
- tests/models/test_patch_predictor.py
- tests/models/test_semantic_segmentation.py
- tiatoolbox/models/engine/nucleus_instance_segmentor.py
- tiatoolbox/models/engine/semantic_segmentor.py
Carry on from #285 with a dedicated branch for this fix.
Linked to #287 
Check list:
@ByteHexler To add clarification on the origin of this performance issue. 
https://github.com/TissueImageAnalytics/tiatoolbox/blob/ca0ece69e0f1cd110687a391b9aed882597c46d9/tiatoolbox/models/engine/semantic_segmentor.py#L670-L673
`self._process_predictions` is called every time `cum_output` is updated. We will process `n**2` time compared to the normal `n` times. As such, depending on the size of the WSI, this can lead to a significant slowdown, and potentially crash the system because many machines won't be able to hold an entire WSI in the memory. In the initial design, we assumed that
https://github.com/TissueImageAnalytics/tiatoolbox/blob/ca0ece69e0f1cd110687a391b9aed882597c46d9/tiatoolbox/models/engine …
> BUG: Fixed Performance Issue In semantic_segmentor.py

- setup.cfg
- tests/models/test_arch_micronet.py
- tests/models/test_nucleus_instance_segmentor.py
- tests/test_annotation_stores.py
- tests/test_pyramid.py
- tests/test_slide_info.py
- tests/test_stainnorm.py
- tests/test_wsireader.py
- tiatoolbox/data/__init__.py
This should ignore all DeepSource warnings about generating paths in test files. This is an issue with PyTest `tmp_path`. This might not be the only/best way to do this, but is the best fix I can think of for now to prevent PRs from being blocked.
> DEV: Ignore `tmp_path` Paths For DeepSource

- tests/test_annotation_stores.py
- tiatoolbox/annotation/storage.py
Fix for test_annotation_stores.py
This has been failing due to a change in the compile flags of recent versions of sqlite3. JSON functions are now a core component of SQLite, not an extension that must be enabled via a compile option. Because of this the ENABLE_JSON1 flag was removed and OMIT_JSON flag added. 
For more info see: https://sqlite.org/src/doc/json-enhancements/doc/json-enhancements.md
The fix just adds a version check, and checks the compile options appropriately to the version.
> BUG: Update sqlite compile option checking

- tiatoolbox/models/architecture/__init__.py
- tiatoolbox/models/architecture/hovernet.py
- tiatoolbox/models/architecture/idars.py
- tiatoolbox/models/architecture/micronet.py
- tiatoolbox/models/engine/patch_predictor.py
- tiatoolbox/models/engine/semantic_segmentor.py
Added tables of metrics to the documentation of TIAToolbox.
> DOC: Add Metrics Tables To Documentation

- tests/models/test_feature_extractor.py
- Fix Errors after torch upgrade to v1.12
The issue seems to be due change in output dtype in torch v1.12 which affects precision https://github.com/pytorch/pytorch/releases
> BUG: Fix Errors After Torch Upgrade To Version 1.12

- requirements.dev.conda.yml
"make html" fails without nbsphinx
> DEV: Restore `nbsphinx` To `requirements.dev.conda.yml`

- requirements.dev.conda.yml
- tests/models/test_multi_task_segmentor.py
- tests/models/test_semantic_segmentation.py
This PR simply sets the number of works used in tests to use the `multiprocessing.cpu_count()` with a fallback to 2.
> TST: Set Test Number of Workers Based on CPU Count

- tests/test_wsireader.py
- tiatoolbox/wsicore/wsireader.py
- whitelist.txt
- Add path check to WSIReader base init
- Minor refactoring / renaming
- Add to parameterized WSIReader test (Add JP2 and improve content checks - corrcoef could be NaN).
> BUG: Check That An Input Path Actually Exists

- .github/workflows/python-package.yml
- CITATION.cff
- HISTORY.md
- setup.cfg
- setup.py
- tiatoolbox/__init__.py
- tiatoolbox/cli/__init__.py
- Bump version: 1.1.0 → 1.2.0
- Fixes Python version info
- Adds support for Python 3.10
- Adds short description for IDARS algorithm #383
- Adds support for NGFF v0.4 [OME-ZARR](https://ngff.openmicroscopy.org/latest/).
- Adds CLI for launching tile server. 
- Renames `stainnorm_target()` function to `stain_norm_target()`.
- Removes `get_wsireader`
- Replaces the custom PlattScaler in `tools/scale.py` with the regular Scikit-Learn [LogisticRegression](https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression).
- Fixes bugs in UNET architecture.
- Number of channels in Batchnorm argument in the decoding path to match with the input channels.
- Padding `0` creates feature maps in the decoder part with the same size as encoder.
- Fixes linter issues and typos
- Fixes …
> [Skip Travis] REL: Release 1.2.0

- .pre-commit-config.yaml
- pre-commit/notebook_check_ast.py
Add a simple pre-commit check which iterates over code cells in each notebook file and checks that any lines which don't start with a ! are valid python, i.e. that they parse to an abstract syntax tree (AST).
This PR also removes a broken and unused old hook.
> DEV: Add Notebook AST Pre-Commit Hook

- tests/conftest.py
- tests/test_docs.py
- tiatoolbox/tools/pyramid.py
- tiatoolbox/utils/misc.py
- tiatoolbox/utils/transforms.py
- tiatoolbox/visualization/tileserver.py
- whitelist.txt
This adds a unit test which will:
1. Check that all docstring examples have a valid python syntax (checks that they parse to an abstract syntax tree).
2. That the imports in the example can be resolved.
3. Report exact source line number and reason for violation.
This has been used to correct several errors in docstring examples in this PR (See examples below).
This avoids actually executing the code. This is good for checking examples that:
- Require network access.
- Download large files.
- Require a GPU.
- Take a long time to run.
- Use dummy variables.
This could potentially be a pre-commit hook instead. The import detection part works well as a unit test because it uses the already set up environment of dependencies. This could however be done with a cached conda env hook. It can …
> TST: Validate Docstring Examples

- tests/test_docs.py
- tiatoolbox/annotation/storage.py
This PR improves the error output from docstring tests which fail by reducing error output and highlighting the offending line in the output.
This also fixes an error in a docstring which triggered the failing test.
> ENH: Improve Docstring Validity Test Error Output

- tiatoolbox/models/engine/nucleus_instance_segmentor.py
Correct error in nucleus instance segmentor engine where for tiles of different size widths/heights there are boundary artefacts.
> BUG: Correct error in nucleus instance segmentor engine

- tiatoolbox/models/engine/semantic_segmentor.py
Corrects a single typo in a python module
> DOC: Spell Output Correctly

- CITATION.cff
- README.md
- Update citation in README.md and CITATION.cff
> [skip ci] DOC: Update citation in README.md and CITATION.cff

- README.md
- tests/test_tileserver.py
- tiatoolbox/cli/show_wsi.py
- tiatoolbox/tools/registration/wsi_registration.py
- tiatoolbox/utils/metrics.py
- tiatoolbox/utils/misc.py
- Fix FLK-D202 No blank lines allowed after function docstring
> [skip ci] BUG: Fix FLK-D202 No blank lines allowed after function docstring

- tests/models/test_patch_predictor.py
Stops test function from dumping a file to the project root. Uses `tmp_path` instead.
As a side note (maybe another PR). This test should be split up. Multiple `pytest.raises` and `assert` statements is a sign that the test should be split up. This test had a lot of them!
> 🗑️  TST: Prevent Fly Tipping

- docs/requirements.txt
- requirements.txt
- setup.cfg
- tests/models/test_arch_micronet.py
- tests/models/test_nucleus_instance_segmentor.py
- tests/test_annotation_stores.py
- tests/test_dsl.py
- tests/test_pyramid.py
- tests/test_slide_info.py
- tests/test_stainnorm.py
- tests/test_wsimeta.py
- tests/test_wsireader.py
- Update `setup.cfg` for flake8 E800.
- Enables `E800` checks - "Found commented out code".
- Remove DeepSource ignore flags from test files.
- Update `requirements.txt` files
- Move comment in `setup.cfg` which is now causing an error.
- Fix DeepSource Errors.
> DEV: Fix Flake8 E800 for tests

- setup.cfg
- tests/test_data.py
- tiatoolbox/data/__init__.py
This mirrors a subset of changes from #503 to add a sample SVS loading function `tiatoolbox.data.small_svs()` to the data module for use in documentation examples.
> DOC: Copy Sample SVS Loader From docs-examples-1

- docs/pretrained.rst
- tiatoolbox/data/pretrained_model.yaml
- tiatoolbox/models/architecture/sccnn.py
- Update API for SCCNN to be consistent
- Add documentation for mapde and sccnn
- Add documentation for micronet
> :boom: API: Change API for SCCNN input

- tiatoolbox/models/architecture/micronet.py
- Fix scipy deprecation
-  Please use `label` from the `scipy.ndimage` namespace, the `scipy.ndimage.measurements` namespace is deprecated.
> :arrow_up: DEP: Remove Scipy Deprecated Code

- tests/test_init.py
- tests/test_tiatoolbox.py
- tiatoolbox/__init__.py
- Filter logger output to `stdout` instead of `stderr`
> :wrench: DEV: Filter Logger Output to `stdout` and `stderr`

- tests/models/test_arch_idars.py
- tests/models/test_arch_mapde.py
- tests/models/test_arch_micronet.py
- tests/models/test_arch_nuclick.py
- tests/models/test_arch_sccnn.py
- tests/models/test_hovernet.py
- tests/models/test_hovernetplus.py
- tiatoolbox/models/__init__.py
- Move the following models to top-level import
- HoVerNet
- HoVerNetPlus
- IDaRS
- MapDe
- MicroNet
- NuClick
- SCCNN
> :art: Move Models to Top-Level Import

- tests/test_wsireader.py
- tiatoolbox/wsicore/wsireader.py
- whitelist.txt
> 🩹 BUG: Fix Parsing Missing Omero Version NGFF Metadata

- pyproject.toml
- setup.cfg
- Use `pyproject.toml` for `bdist_wheel` configuration
- Remove `aliases`
> :wrench: Use `pyproject.toml` for `bdist_wheel` Configuration

- pyproject.toml
- Use `pyproject.toml` for `pytest` Configuration
> 🔧 Use `pyproject.toml` for `pytest` Configuration

- tiatoolbox/wsicore/wsireader.py
wsidicom has been updated today. I noticed it makes a change which breaks one of the tests.
our code gets the base level as `dataset = self.wsi.base_level.datasets[0]`
The WsiDicom object has recently been changed so that this base_level is no longer a property of WsiDicom object, it is instead now only in `self.wsi.levels.base_level.datasets[0]` (before the update it was in both).
See [here](https://github.com/imi-bigpicture/wsidicom/commit/90671211ddb87096d19952d5e80a7199dda51b67#diff-c193bbcec87f294abe8cc7a11e0ff209eea7d49407ff301734499e8956477501L98-L101), line 98-101 in wsidicom.py diff.
> 🐛 Fix for Recent `wsidicom` Update

- tests/test_annotation_stores.py
- tests/test_annotation_tilerendering.py
- tests/test_init.py
- tiatoolbox/__init__.py
- tiatoolbox/annotation/storage.py
- tiatoolbox/tools/pyramid.py
- Use `logger` Instead Of `warnings` for `pyramid.py` and `storage.py`
- Catches duplicate errors and prints them only once.
> 🚨 Use `logger` Instead Of `warnings` for `pyramid.py` and `storage.py`

- tests/test_annotation_tilerendering.py
- tests/test_utils.py
- tiatoolbox/utils/image.py
- tiatoolbox/utils/misc.py
- tiatoolbox/utils/visualization.py
- Use `logger` Instead Of `warnings` for `utils` Package
> 🚨 Use `logger` Instead Of `warnings` for `utils` Package

- pre-commit/notebook_urls.py
- tests/models/test_patch_predictor.py
- tests/test_wsireader.py
- tiatoolbox/annotation/storage.py
- tiatoolbox/models/architecture/unet.py
- tiatoolbox/tools/stainaugment.py
- tiatoolbox/wsicore/metadata/ngff.py
- tiatoolbox/wsicore/wsireader.py
- Fix Multi-line docstring closing quotes should be on a separate line FLK-D209
- Fix No blank lines allowed after function docstring FLK-D202
- Fix Doc line too long FLK-W505
- Fix Attribute defined outside __init__ PYL-W0201
- Fix Function contains unused argument PYL-W0613
- Fix Consider decorating method with @staticmethod PYL-R0201
- Fix Missing module/function docstring PY-D0003
> 🐛 Fix `deepsource` Errors

- tests/test_docs.py
- tiatoolbox/models/engine/multi_task_segmentor.py
- Fix `test_validate_docstring_examples`
- Revert to `test_validate_docstring_examples` execution in CI, as now it passes
> 🐛 Fix `MultiTaskSegmentor` Example

- tests/test_wsi_registration.py
- tiatoolbox/tools/registration/wsi_registration.py
- Use `logger` Instead Of `warnings` for `wsi_registration.py`
- Refactor duplicate code fragments
> 🚨 Use `logger` Instead Of `warnings` for `wsi_registration.py`

- tiatoolbox/wsicore/__init__.py
- Use `__all__` for high level imports
> :recycle: Use `__all__` for High Level Imports

- tiatoolbox/models/architecture/vanilla.py
- tiatoolbox/tools/registration/wsi_registration.py
- Replace deprecated input `pretrained` with `weights` according to the new API.
> :recycle: Replace deprecated input `pretrained` with `weights`

- tiatoolbox/annotation/storage.py
- tiatoolbox/utils/visualization.py
- Remove `shapely.speedups`.
- [The shapely.speedups module (the enable and disable functions) is deprecated and will be removed in the future. The module no longer has any affect in Shapely >=2.0.](https://shapely.readthedocs.io/en/stable/release/2.x.html#shapely-2-0-api-changes-deprecated-in-1-8)
> :wastebasket: Remove `shapely.speedups`

- tests/models/test_arch_mapde.py
- Reduce run time for Mapde test.
> :white_check_mark: Reduce run time for Mapde test

- tests/models/test_arch_micronet.py
> :test_tube: Improve `micronet` Tests

- CONTRIBUTING.rst
- pyproject.toml
- requirements/requirements_dev.txt
- setup.cfg
- tiatoolbox/__init__.py
- Use [`poetry-bumpversion`](https://pypi.org/project/poetry-bumpversion/) for version number updates instead of bump2version as bump2version is no longer being maintained https://github.com/c4urself/bump2version/issues/42#issuecomment-1582436696.
> :technologist: Use `poetry` for Version Updates

- tests/test_wsireader.py
- Reduce Test runtime for JP2 `test_fuzz_read_region_baseline_size`
- This test takes longest time to run on CI. Number of iterations is quite high which can be reduced to improve tests run time.
> :technologist: Reduce Test runtime for JP2

- tests/conftest.py
- tests/test_utils.py
- tiatoolbox/utils/env_detection.py
`model.to('cuda')` on my m1-based mac (mps backed) raises AssertionError, not Runtime one:
```            if not hasattr(torch._C, '_cuda_getDeviceCount'):
>               raise AssertionError("Torch not compiled with CUDA enabled")
E               AssertionError: Torch not compiled with CUDA enabled
```
Also, improved Ci-detection behaviour.
> :recycle: Small tests improvements

- tests/test_wsi_registration.py
- tiatoolbox/tools/registration/wsi_registration.py
Likewise other intermediate transform, Phase cross-correlation transform should only be applied if it improves the DICE overlap.
> Add check for Phase correlation transform

- benchmarks/annotation_store_alloc.py
- pre-commit/missing_imports.py
- pre-commit/notebook_check_ast.py
- pre-commit/requirements_consistency.py
- tests/test_exceptions.py
- tests/test_patch_extraction.py
- tests/test_utils.py
- tests/test_visualization.py
- tests/test_wsireader.py
- tiatoolbox/tools/graph.py
- tiatoolbox/tools/patchextraction.py
- tiatoolbox/tools/pyramid.py
- tiatoolbox/tools/registration/wsi_registration.py
- tiatoolbox/tools/stainaugment.py
- tiatoolbox/tools/stainextract.py
- tiatoolbox/tools/stainnorm.py
- tiatoolbox/tools/tissuemask.py
- tiatoolbox/utils/env_detection.py
- tiatoolbox/utils/exceptions.py
- tiatoolbox/utils/magic.py
- tiatoolbox/utils/misc.py
- tiatoolbox/utils/transforms.py
- tiatoolbox/utils/visualization.py
- tiatoolbox/wsicore/wsireader.py
- whitelist.txt
- Fix linter error in `tools`, `utils` and `pre-commit` from #625
> 🚨 Fix Linter Error in `tools`, `utils` and `pre-commit`

- .github/workflows/docker-publish.yml
- CITATION.cff
- HISTORY.md
- setup.cfg
- setup.py
- tiatoolbox/__init__.py
- Fix dictionary changed size Error #626 (#605)
> 🚑 Release 1.4.1

- .pre-commit-config.yaml
- pyproject.toml
- requirements/requirements_dev.txt
- tests/models/test_dataset.py
- tests/models/test_patch_predictor.py
- Remove `isort` 
- Use `ruff` for sorting imports
> ➖ Remove `isort` and Use `ruff` for sorting imports

- tiatoolbox/tools/registration/wsi_registration.py
- Fix issues when extracting transformed patches using `mpp` and `power` units
> 🐛 Fix `AffineWSITransformer.read_rect()`

- tests/models/test_feature_extractor.py
- tests/models/test_multi_task_segmentor.py
- tests/models/test_nucleus_instance_segmentor.py
- tests/models/test_patch_predictor.py
- tests/models/test_semantic_segmentation.py
- Remove redundant `_rm_dir` in tests.
> :fire: Remove redundant `_rm_dir` in tests.

- tiatoolbox/tools/patchextraction.py
One of the arguments to the various PatchExtractors has an incorrect description. This PR fixes it.
> 📝 Fix Docstrings in `PatchExtractor`

- tiatoolbox/data/pretrained_model.yaml
Quick PR to fix the `ioconfig` bug with NuClick in the pretrained models yaml file.
> 🐛 Add `IOConfig` for NuClick in `pretrained_model.yaml`

- tests/test_patch_extraction.py
- tiatoolbox/tools/patchextraction.py
proposed fix for issue #710 
fixes situation where PatchExtractor.get_coords() can return patch coords which lie fully outside the bounds of a slide.
Also adds a test that would have flagged this situation.
> 🐛 Fix `patch_coords`

- pyproject.toml
- tests/test_annotation_stores.py
- tests/test_annotation_tilerendering.py
- tests/test_dsl.py
- tiatoolbox/annotation/dsl.py
- tiatoolbox/annotation/storage.py
- Fix flake8-annotation errors in tests and annotation.
To review:
- Please review `AnnotationStore` type hints for `*args` `**kwargs`
- Please review where Ruff errors are ignored for `Any` datatype (ANN401, F821)
- Please review where Ruff errors are ignored for unused arguments (ARG001)
> 🚨 Fix `flake8-annotation` Linter Errors

- .github/workflows/mypy-type-check.yml
- tests/test_init.py
- tiatoolbox/__init__.py
Add type checking using `mypy`, a static type checker for Python.
This PR involves adding type hints and checking the correctness of existing type hints in the code base.
A GitHub action has been created to run `mypy` after push and pull requests.
Currently, only `tiatoolbox/__init__.py` has been checked to work without errors with `mypy`.
> :construction: Add type checking using `mypy`

- .github/workflows/mypy-type-check.yml
- tiatoolbox/typing.py
- tiatoolbox/utils/image.py
- tiatoolbox/utils/transforms.py
- Add `mypy` checks to `image.py`
> :white_check_mark: Add `mypy` checks to `image.py`

- .github/workflows/docker-publish.yml
- AUTHORS.md
- CITATION.cff
- HISTORY.md
- pyproject.toml
- setup.py
- tiatoolbox/__init__.py
- tiatoolbox/annotation/storage.py
- Adds the bokeh visualization tool. #684
- The tool allows a user to launch a server on their machine to visualise whole slide images, overlay the results of deep learning algorithms or to select a patch from whole slide image and run TIAToolbox deep learning engines.
- This tool powers the TIA demos server. For details please see https://tiademos.dcs.warwick.ac.uk/.
- Extends Annotation to Support Init from WKB #639
- Adds `IOConfig` for NuClick in `pretrained_model.yaml` #709
- Adds functions to save the TIAToolbox Engine outputs to Zarr and AnnotationStore files. #724
- Adds Support for QuPath Annotation Imports #721
- Adds `model.to(device)` and `model.load_model_from_file()` functionality to make it compatible with PyTorch API. #733
- Replaces `pretrained` with `weights` to make the …
> 🔖 Release 1.5.0

- setup.py
- Specify Python versions to be >=3.8 and <3.12
> :pushpin: Specify Python versions

- .github/workflows/docker-publish.yml
- CITATION.cff
- HISTORY.md
- pyproject.toml
- setup.py
- tiatoolbox/__init__.py
- Specifies compatible Python versions
- Fixes `tiatoolbox-feedstock` build for conda-forge release #763
**Full Changelog:** https://github.com/TissueImageAnalytics/tiatoolbox/compare/v1.5.0...v1.5.1
> 🚑 Release 1.5.1

- requirements/requirements.txt
- tiatoolbox/annotation/storage.py
Removes the use of POWER from distance calculations to address issue #692
Replaces use of POWER with explicit multiplication.
> ♻️ Remove `POWER` from sqlite-dist Calculations

- tests/test_annotation_stores.py
- tests/test_stainnorm.py
Can no longer pass None to pytest.warns(). This is why tests were failing recently in test_annotation_stores.py. See: https://docs.pytest.org/en/latest/deprecations.html#using-pytest-warns-none
They seem to have left no convenient way to test for no warnings using pytest.warns(), so I have rewritten that test to explicitly check that the warning doesn't exist in the log.
Unfortunately, tests are also failing in test_stainnorm.py due to an error:
```
FAILED tests/test_stainnorm.py::test_cli_stainnorm_dir - AssertionError: assert 1 == 0
where 1 = <Result LinAlgError('SVD did not converge in Linear Least Squares')>.exit_code
```
I have no idea why this is happening and cannot replicate it on my machine, it may be related to the age old problem of vahadane normalization being flaky as that is …
> 🐛Fix `test` in `test_annotation_stores.py`

- tests/test_dsl.py
- tiatoolbox/annotation/dsl.py
Restructures the way the dsl builds the SQL expression to access JSON properties so that properties with a . in are correctly treated as a single key
Adds a test to check for correct behaviour when accessing a property containing a .
Addresses issue #771 
Would like to check with John if removing json.dumps() is ok. I couldn't see a reason it was necessary and all tests pass/all the use-cases I tried worked fine, but maybe there is one I missed.
> 🐛 Fix `json_extract` Construction

- tiatoolbox/__init__.py
- tiatoolbox/cli/visualize.py
- Refactor `cli.visualize` to Improve `cli` Response
Before applying fix `$ time python -m tiatoolbox -h`
real    0m18.525s
user    0m17.144s
sys     0m3.077s
After applying the fix `$ time python -m tiatoolbox -h`
real    0m1.053s
user    0m0.434s
sys     0m0.020s
> :children_crossing: Refactor `cli.visualize` to Improve `cli` Response

- tests/test_app_bokeh.py
- tiatoolbox/visualization/bokeh_app/main.py
Bokeh 3.4 depreciated size in favor of radius in circle glyphs (you used to be able to use either, now only radius exists) and so tests now fail since 3.4.
This PR replaces all references to 'size' in circle glyphs with corresponding 'radius' for compatibility with bokeh 3.4.
> :alien: Change `size` to `radius` for `bokeh 3.4` Compatibility

- .github/workflows/python-package.yml
- Fix `codecov` Reporting
Fixes the following error:
```
[2024-04-26T13:26:38.358Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
[2024-04-26T13:26:38.358Z] ['verbose'] The error stack is: Error: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', …
```
> :bug: Fix `codecov` Reporting

- tests/conftest.py
- tests/test_wsireader.py
- tiatoolbox/data/remote_samples.yaml
- tiatoolbox/wsicore/wsireader.py
Fix Code Complexity in `wsireader`
- Fixes `PLR0912`, `C901`
- Improves coverage to include cases with regular tiff files.
> 🐛 Fix Code Complexity in `wsireader`

- tests/test_annotation_stores.py
- tests/test_init.py
- Logger filters need to be reset at the start of run. This is required if a failed test with logs is run in another pytest.
- This PR fixes [failed tests](https://github.com/TissueImageAnalytics/tiatoolbox/actions/runs/9414105193/job/25932262521) in #783.
> :white_check_mark: Add Test to Reset `logger` Filters.

- requirements/requirements.txt
-  Pin `bokeh` to `<3.5.0` Due to Incompatibility.
> :pushpin: Pin `bokeh` to `<3.5.0` Due to Incompatibility.

- .github/workflows/python-package.yml
- requirements/requirements_dev.txt
- tests/test_dsl.py
- The new version of `pytest` (>=8.3.0) does not update variables properly in different scenarios. This causes the tests to fail. As a fix I have nested variables in a dictionary and then parse them for each function.
- Remove pin from `pytest` version.
> :bug: Fix `test_dsl` for `pytest`>=8.3.0

- tiatoolbox/utils/transforms.py
- Resolve issue #837 
The output of WSI readers (read_rect, read_region, etc) are immutable, i.e. Read-only. We assume that created Numpy arrays created from PIL images in the `background_composite` are mutable by default.
After Numpy v1.16.0, doing np.asarray(pil_image) will return an immutable Numpy array. Gladly, there is an easy fix for this, we should use `np.array()` instead of `np.asarray`.
> 🐛 Fix Immutable Output from `WSIReader`

- requirements/requirements_dev.txt
-  `jinja2` was explicitly pinned for breaking changes in `sphinx`.
- `sphinx` manages this dependency on its own.
> :heavy_minus_sign: Remove `jinja2` dependency

- requirements/requirements.txt
- Pin `bokeh` version to less than `3.6.0`
- `bokeh` 3.6.0 has breaking changes
> :pushpin: Pin `bokeh` version to less than 3.6.0

- tests/test_patch_extraction.py
- tiatoolbox/tools/patchextraction.py
- tiatoolbox/utils/misc.py
> 🧑‍💻 Refine `PatchExtractor` Error Message

- tiatoolbox/models/architecture/utils.py
- `torch.compile` is not currently compatible with Windows. See https://github.com/pytorch/pytorch/issues/122094
> :technologist: Add Warning for `torch.compile` on Windows.

- requirements/requirements.txt
Zarr 3.0 breaks lots of things, probably wont be a quick fix to make toolbox compatible with it, so probably best to pin <3.0 for now
See: https://zarr.readthedocs.io/en/latest/user-guide/v3_migration.html  and #904 for more details
> 📌 Pin `zarr<3.0.0`

- tests/models/test_arch_mapde.py
- tests/models/test_arch_sccnn.py
- If cuda is available model should be moved to cuda otherwise tests will fail as test data is moved to cuda.
> 🐛 Fix in `test_arch_mapde` and `test_arch_sccnn`

- tests/models/test_arch_mapde.py
- tiatoolbox/models/architecture/mapde.py
- Fix `dist_filter` in `MapDe` model for multi-class output.
Explanation:
Previously, if we set `num_class` to more than 1, the model would still output 1 channel. This was because the `dist_filter` always had size of 1 in its first dimension, however the first dimension determines the number of output channels in the tensor produced by `torch.functional.F.conv2d`.
I changed this by simply repeating the filters the match the number of output classes.
> :bug: Fix `MapDe` `dist_filter` Shape 

- tiatoolbox/wsicore/wsireader.py
Unnecessary logging was introduced in the https://github.com/TissueImageAnalytics/tiatoolbox/pull/897
The error log now appears in the console on every WSI read.
> :mute: Remove Unnecessary Logging

- tiatoolbox/tools/patchextraction.py
- tiatoolbox/tools/registration/wsi_registration.py
- tiatoolbox/utils/transforms.py
- tiatoolbox/utils/visualization.py
Revisited some of the files from `tools`/ and `utils/`, updated typing for them.
> 🔧 `mypy` type check `tools/` and `utils/`

- tests/test_utils.py
- tiatoolbox/utils/misc.py
- This PR saves a NumPy or Zarr Array to OME tiff. This will help to save probability maps from deep learning models as ome.tiff which can be visualized using TIAViz.
- The image is written as tiles and stitched in OME tiff along with associated necessary metadata for heatmaps generated by segmentation engine.  #866 
- Reading with QuPath has been tested.
> ✨ Add Feature to Write Model Probabilities as `ome.tiff` for Overlay

- tiatoolbox/visualization/tileserver.py
This PR fixes a bug that occurs when multiple slides are loaded into the TileServer and multiple annotation overlays are subsequently uploaded in sequence.
Steps to reproduce:
1. Load Slide 1 into the TileServer.
2. Load Slide 2 into the TileServer.
3. Upload the annotation overlay (GeoJSON) for Slide 1 via the /tileserver/overlay endpoint.
4. Upload the annotation overlay (GeoJSON) for Slide 2 via the /tileserver/overlay endpoint.
5. Attempt to load the overlay for Slide 1 via the /tileserver/layer/overlay/default/zoomify/ endpoint.
Expected behavior:
The annotation overlay for Slide 1 is displayed.
Actual behavior:
The annotation overlay for Slide 2 is displayed instead.
> 🐛 Fix Consecutive Annotations Load Bug

- requirements/requirements.txt
This PR refines the dependency version requirements by pinning tifffile with an explicit upper bound.  
- Pin tifffile with both a minimum version (2022.10.10) and maximum version (2025.5.10).  
- This ensures controlled compatibility for tifffile across environments.
> :pushpin: Pin `tifffile<=2025.5.10`

- .github/workflows/mypy-type-check.yml
- requirements/requirements_dev.txt
- tiatoolbox/tools/pyramid.py
Fixed typing issue in `pyramid.py`.
> 🔧 `mypy` fix typing in `pyramid.py`

- tiatoolbox/utils/visualization.py
- Add examples in docstrings for `utils.visualization`.
> 📝 Add `utils.visualization` Examples

- tiatoolbox/utils/misc.py
This PR fixes the problem of dict_to_store_semantic_segmentor failing to handle holes properly. The problem was, that the code was not associating the holes with the correct parent contour.
For a segmentation mask like:
Old code would give an annotation store looking like:
With this PR, that store now looks like:
> 🐛 Fix Contours with Holes
